
mysql_container_name: "mysql"
mysql_image: "mysql/mysql-server:5.7"

MYSQL_ROOT_PASSWORD: "YES"
MYSQL_PORT: "3306"
MYSQL_DATA_DIR: "mysql_data"
MYSQL_USER: "microblog"
MYSQL_PASSWORD: "alai20sogi20"
MYSQL_DATABASE: "microblog"

