global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          instance: node-exporter
  - job_name: "promethues"
    static_configs:
      - targets: ['0.0.0.0:9090']
        labels:
          instance: promethues
  - job_name: "flask"
    static_configs:
    - targets: ['prod:5000']
      labels:
        instance: flask