# deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microblog
spec:
  selector:
    matchLabels:
      app: microblog
  replicas: 2
  template:
    metadata:
      labels:
        app: microblog
    spec:
      containers:
      - image: alai20/microblog:14.0.2
        imagePullPolicy: Always
        name: microblog
        resources:
          requests:
            cpu: "250m"
          limits:
            cpu: "500m"
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_USER

        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_DATABASE

        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: DB_PASSWORD

        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: ROOT_PASSWORD

        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: SECRET_KEY

        - name: DATABASE_URL
          value: "mysql+pymysql://$(MYSQL_USER):$(MYSQL_PASSWORD)@mysql:3306/$(MYSQL_DATABASE)"

        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /
            port: 5000

