# mysql-secrets.yml
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  MYSQL_USER: bWljcm9ibG9n
  MYSQL_DATABASE: bWljcm9ibG9n
  DB_PASSWORD: bWljcm9wYXNzdw==
  ROOT_PASSWORD: c29naTIwYWxhaTIw
  SECRET_KEY: c29naTIwYWxhaTIw
