---
# Here you can add variables that will be available for all hosts.
ansible_python_interpreter: "python3"

region: northeurope
resource_group: DIDA-ALAI20-DV1673-H25-LP2 # Change me
domain_name: alexanderw.me # Change me

admin_email: alai20@student.bth.se

vmtags:
    StudentId: alai20 # Change me


pub_ssh_key_location: '/home/alexanderw/.ssh/azure_devops.pub' # Change me, your local ssh key!


server_user: "deploy"
server_user_pass: "sogi20alai20" # change me
server_user_groups:
    -   sudo
