---
    -   hosts: appserver
        serial: 1 # Is this the only thing needed?
        remote_user: "deploy"
        become: yes
        become_method: sudo
        roles:
            -   install_docker
            -   deploy_app