name: Security Check

on:
  workflow_call: {}

permissions:
  contents: read
  packages: write

jobs:
  security-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: |
            requirements/prod.txt
            requirements/test.txt

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/test.txt

      - name: Install Trivy
        run: |
          apt install trivy

      # - name: Install dockle ?!
      #   run: |
      #     idk?
      
      - name: Run Bandit
        run: |
          make bandit
      
      - name: Run Trivy
        run: |
          make trivy

      # - name: Run dockle
      #   run: |
      #     make dockle