name: Security Check

on:
  workflow_call: {}

permissions:
  contents: read
  packages: write

jobs:
  security-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: |
            requirements/prod.txt
            requirements/test.txt

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/test.txt

      - name: Install Trivy
        run: |
          apt install trivy

      - name: Install dockle
        run: |
          VERSION=$(
          curl --silent "https://api.github.com/repos/goodwithtech/dockle/releases/latest" | \
          grep '"tag_name":' | \
          sed -E 's/.*"v([^"]+)".*/\1/' \
          ) && curl -L -o dockle.deb https://github.com/goodwithtech/dockle/releases/download/v${VERSION}/dockle_${VERSION}_Linux-64bit.deb
          $ sudo dpkg -i dockle.deb && rm dockle.deb
      
      - name: Run Bandit
        run: |
          make bandit
      
      - name: Run Trivy
        run: |
          make trivy

      - name: Run dockle
        run: |
          make dockle